Fix After switch to switchPreferenceCompat
FATAL EXCEPTION: main
Process: com.android.settings, PID: 19150
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.ClassCastException: com.afterlife.support.preference.SecureSettingSwitchPreference cannot be cast to androidx.preference.SwitchPreference

Change-Id: Ifb09faa592490edbc799977ec28f3dff8ebb1a73
Signed-off-by: muthafuka X <muthafuka21@gmail.com>